# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from secret_santa.models.base_model_ import Model
from secret_santa import util


class ParticipantDetails(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, first_name: str=None, last_name: str=None):  # noqa: E501
        """ParticipantDetails - a model defined in Swagger

        :param first_name: The first_name of this ParticipantDetails.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this ParticipantDetails.  # noqa: E501
        :type last_name: str
        """
        self.swagger_types = {
            'first_name': str,
            'last_name': str
        }

        self.attribute_map = {
            'first_name': 'firstName',
            'last_name': 'lastName'
        }
        self._first_name = first_name
        self._last_name = last_name

    @classmethod
    def from_dict(cls, dikt) -> 'ParticipantDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ParticipantDetails of this ParticipantDetails.  # noqa: E501
        :rtype: ParticipantDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def first_name(self) -> str:
        """Gets the first_name of this ParticipantDetails.


        :return: The first_name of this ParticipantDetails.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this ParticipantDetails.


        :param first_name: The first_name of this ParticipantDetails.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this ParticipantDetails.


        :return: The last_name of this ParticipantDetails.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this ParticipantDetails.


        :param last_name: The last_name of this ParticipantDetails.
        :type last_name: str
        """

        self._last_name = last_name
