# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from secret_santa.models.base_model_ import Model
from secret_santa import util


class Participation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, participating: bool=None):  # noqa: E501
        """Participation - a model defined in Swagger

        :param participating: The participating of this Participation.  # noqa: E501
        :type participating: bool
        """
        self.swagger_types = {
            'participating': bool
        }

        self.attribute_map = {
            'participating': 'participating'
        }
        self._participating = participating

    @classmethod
    def from_dict(cls, dikt) -> 'Participation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Participation of this Participation.  # noqa: E501
        :rtype: Participation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def participating(self) -> bool:
        """Gets the participating of this Participation.


        :return: The participating of this Participation.
        :rtype: bool
        """
        return self._participating

    @participating.setter
    def participating(self, participating: bool):
        """Sets the participating of this Participation.


        :param participating: The participating of this Participation.
        :type participating: bool
        """

        self._participating = participating
